global using TokenBasedAuthApplication.Business.Services;
global using TokenBasedAuthApplication.Core.Configuration;
global using TokenBasedAuthApplication.Core.Services;
global using TokenBasedAuthApplication.Core.Services.Authentication;
global using TokenBasedAuthApplication.SharedLibrary.Authentication;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Identity;
global using TokenBasedAuthApplication.Business.Services.Common;
global using TokenBasedAuthApplication.Core.DataAccess.Common;
global using TokenBasedAuthApplication.Core.Entities;
global using TokenBasedAuthApplication.Core.Services.Common;
global using TokenBasedAuthApplication.DataAccess.Contexts.EntityFramework;
global using TokenBasedAuthApplication.DataAccess.Repositories.Common;
global using AuthenticationService = TokenBasedAuthApplication.Business.Services.AuthenticationService;
global using IAuthenticationService = TokenBasedAuthApplication.Core.Services.Authentication.IAuthenticationService;