global using TokenBasedAuthApplication.Business.Services;
global using TokenBasedAuthApplication.Core.Configuration;
global using TokenBasedAuthApplication.Core.Services;
global using TokenBasedAuthApplication.Core.Services.Authentication;
global using TokenBasedAuthApplication.SharedLibrary.Authentication;